//// Code generated by protoc-gen-go. DO NOT EDIT.
//// versions:
//// 	protoc-gen-go v1.28.0
//// 	protoc        v3.20.0
//// source: drink.proto
//
//// user 包
//
package protos
//
//import (
//	context "context"
//	grpc "google.golang.org/grpc"
//	codes "google.golang.org/grpc/codes"
//	status "google.golang.org/grpc/status"
//	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
//	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
//	reflect "reflect"
//	sync "sync"
//)
//
//const (
//	// Verify that this generated code is sufficiently up-to-date.
//	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
//	// Verify that runtime/protoimpl is sufficiently up-to-date.
//	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
//)
//
//// 枚举类型
//type EnumUserSex int32
//
//const (
//	EnumUserSex_SEX_INIT   EnumUserSex = 0 // 枚举类型必须以 0 起始
//	EnumUserSex_SEX_MALE   EnumUserSex = 1
//	EnumUserSex_SEX_FEMALE EnumUserSex = 2
//)
//
//// Enum value maps for EnumUserSex.
//var (
//	EnumUserSex_name = map[int32]string{
//		0: "SEX_INIT",
//		1: "SEX_MALE",
//		2: "SEX_FEMALE",
//	}
//	EnumUserSex_value = map[string]int32{
//		"SEX_INIT":   0,
//		"SEX_MALE":   1,
//		"SEX_FEMALE": 2,
//	}
//)
//
//func (x EnumUserSex) Enum() *EnumUserSex {
//	p := new(EnumUserSex)
//	*p = x
//	return p
//}
//
//func (x EnumUserSex) String() string {
//	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
//}
//
//func (EnumUserSex) Descriptor() protoreflect.EnumDescriptor {
//	return file_drink_proto_enumTypes[0].Descriptor()
//}
//
//func (EnumUserSex) Type() protoreflect.EnumType {
//	return &file_drink_proto_enumTypes[0]
//}
//
//func (x EnumUserSex) Number() protoreflect.EnumNumber {
//	return protoreflect.EnumNumber(x)
//}
//
//// Deprecated: Use EnumUserSex.Descriptor instead.
//func (EnumUserSex) EnumDescriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{0}
//}
//
//type UserEntity struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	UserName   string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
//	UserStatus int32  `protobuf:"varint,2,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
//	UserEmail  string `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
//	UserId     int32  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
//}
//
//func (x *UserEntity) Reset() {
//	*x = UserEntity{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[0]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserEntity) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserEntity) ProtoMessage() {}
//
//func (x *UserEntity) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[0]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserEntity.ProtoReflect.Descriptor instead.
//func (*UserEntity) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{0}
//}
//
//func (x *UserEntity) GetUserName() string {
//	if x != nil {
//		return x.UserName
//	}
//	return ""
//}
//
//func (x *UserEntity) GetUserStatus() int32 {
//	if x != nil {
//		return x.UserStatus
//	}
//	return 0
//}
//
//func (x *UserEntity) GetUserEmail() string {
//	if x != nil {
//		return x.UserEmail
//	}
//	return ""
//}
//
//func (x *UserEntity) GetUserId() int32 {
//	if x != nil {
//		return x.UserId
//	}
//	return 0
//}
//
////用户登录
//type UserIndexRequest struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"` //用户名
//	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                       //邮箱，用户名和邮箱二选一
//	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`                 //用户密码
//}
//
//func (x *UserIndexRequest) Reset() {
//	*x = UserIndexRequest{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[1]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserIndexRequest) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserIndexRequest) ProtoMessage() {}
//
//func (x *UserIndexRequest) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[1]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserIndexRequest.ProtoReflect.Descriptor instead.
//func (*UserIndexRequest) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{1}
//}
//
//func (x *UserIndexRequest) GetUserName() string {
//	if x != nil {
//		return x.UserName
//	}
//	return ""
//}
//
//func (x *UserIndexRequest) GetEmail() string {
//	if x != nil {
//		return x.Email
//	}
//	return ""
//}
//
//func (x *UserIndexRequest) GetPassword() string {
//	if x != nil {
//		return x.Password
//	}
//	return ""
//}
//
//type UserIndexResponse struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Err int32  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
//	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
//}
//
//func (x *UserIndexResponse) Reset() {
//	*x = UserIndexResponse{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[2]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserIndexResponse) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserIndexResponse) ProtoMessage() {}
//
//func (x *UserIndexResponse) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[2]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserIndexResponse.ProtoReflect.Descriptor instead.
//func (*UserIndexResponse) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{2}
//}
//
//func (x *UserIndexResponse) GetErr() int32 {
//	if x != nil {
//		return x.Err
//	}
//	return 0
//}
//
//func (x *UserIndexResponse) GetMsg() string {
//	if x != nil {
//		return x.Msg
//	}
//	return ""
//}
//
//type UserViewRequest struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	UserName   string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"` //用户名
//	Email      string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                       //邮箱，用户名和邮箱二选一
//	UserStatus int32  `protobuf:"varint,3,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
//}
//
//func (x *UserViewRequest) Reset() {
//	*x = UserViewRequest{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[3]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserViewRequest) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserViewRequest) ProtoMessage() {}
//
//func (x *UserViewRequest) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[3]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserViewRequest.ProtoReflect.Descriptor instead.
//func (*UserViewRequest) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{3}
//}
//
//func (x *UserViewRequest) GetUserName() string {
//	if x != nil {
//		return x.UserName
//	}
//	return ""
//}
//
//func (x *UserViewRequest) GetEmail() string {
//	if x != nil {
//		return x.Email
//	}
//	return ""
//}
//
//func (x *UserViewRequest) GetUserStatus() int32 {
//	if x != nil {
//		return x.UserStatus
//	}
//	return 0
//}
//
//type UserViewResponse struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Err int32  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
//	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
//	// 返回一个 UserEntity 对象
//	Data []*UserEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
//}
//
//func (x *UserViewResponse) Reset() {
//	*x = UserViewResponse{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[4]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserViewResponse) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserViewResponse) ProtoMessage() {}
//
//func (x *UserViewResponse) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[4]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserViewResponse.ProtoReflect.Descriptor instead.
//func (*UserViewResponse) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{4}
//}
//
//func (x *UserViewResponse) GetErr() int32 {
//	if x != nil {
//		return x.Err
//	}
//	return 0
//}
//
//func (x *UserViewResponse) GetMsg() string {
//	if x != nil {
//		return x.Msg
//	}
//	return ""
//}
//
//func (x *UserViewResponse) GetData() []*UserEntity {
//	if x != nil {
//		return x.Data
//	}
//	return nil
//}
//
//type UserUpdateRequest struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
//	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
//	Age      int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
//}
//
//func (x *UserUpdateRequest) Reset() {
//	*x = UserUpdateRequest{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[5]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserUpdateRequest) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserUpdateRequest) ProtoMessage() {}
//
//func (x *UserUpdateRequest) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[5]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserUpdateRequest.ProtoReflect.Descriptor instead.
//func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{5}
//}
//
//func (x *UserUpdateRequest) GetName() string {
//	if x != nil {
//		return x.Name
//	}
//	return ""
//}
//
//func (x *UserUpdateRequest) GetPassword() string {
//	if x != nil {
//		return x.Password
//	}
//	return ""
//}
//
//func (x *UserUpdateRequest) GetAge() int32 {
//	if x != nil {
//		return x.Age
//	}
//	return 0
//}
//
//type UserUpdateResponse struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Err int32  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
//	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
//}
//
//func (x *UserUpdateResponse) Reset() {
//	*x = UserUpdateResponse{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[6]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserUpdateResponse) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserUpdateResponse) ProtoMessage() {}
//
//func (x *UserUpdateResponse) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[6]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserUpdateResponse.ProtoReflect.Descriptor instead.
//func (*UserUpdateResponse) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{6}
//}
//
//func (x *UserUpdateResponse) GetErr() int32 {
//	if x != nil {
//		return x.Err
//	}
//	return 0
//}
//
//func (x *UserUpdateResponse) GetMsg() string {
//	if x != nil {
//		return x.Msg
//	}
//	return ""
//}
//
//type UserDeleteRequest struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	UserId   int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
//	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
//}
//
//func (x *UserDeleteRequest) Reset() {
//	*x = UserDeleteRequest{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[7]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserDeleteRequest) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserDeleteRequest) ProtoMessage() {}
//
//func (x *UserDeleteRequest) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[7]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserDeleteRequest.ProtoReflect.Descriptor instead.
//func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{7}
//}
//
//func (x *UserDeleteRequest) GetUserId() int32 {
//	if x != nil {
//		return x.UserId
//	}
//	return 0
//}
//
//func (x *UserDeleteRequest) GetUserName() string {
//	if x != nil {
//		return x.UserName
//	}
//	return ""
//}
//
//type UserDeleteResponse struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Err int32  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
//	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
//}
//
//func (x *UserDeleteResponse) Reset() {
//	*x = UserDeleteResponse{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[8]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserDeleteResponse) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserDeleteResponse) ProtoMessage() {}
//
//func (x *UserDeleteResponse) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[8]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserDeleteResponse.ProtoReflect.Descriptor instead.
//func (*UserDeleteResponse) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{8}
//}
//
//func (x *UserDeleteResponse) GetErr() int32 {
//	if x != nil {
//		return x.Err
//	}
//	return 0
//}
//
//func (x *UserDeleteResponse) GetMsg() string {
//	if x != nil {
//		return x.Msg
//	}
//	return ""
//}
//
//type UserRegisterRequest struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	UserName      string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
//	UserEmail     string `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
//	UserPassword  string `protobuf:"bytes,3,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
//	UserSessionId string `protobuf:"bytes,4,opt,name=user_session_id,json=userSessionId,proto3" json:"user_session_id,omitempty"` //发送给邮件的验证码
//}
//
//func (x *UserRegisterRequest) Reset() {
//	*x = UserRegisterRequest{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[9]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserRegisterRequest) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserRegisterRequest) ProtoMessage() {}
//
//func (x *UserRegisterRequest) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[9]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserRegisterRequest.ProtoReflect.Descriptor instead.
//func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{9}
//}
//
//func (x *UserRegisterRequest) GetUserName() string {
//	if x != nil {
//		return x.UserName
//	}
//	return ""
//}
//
//func (x *UserRegisterRequest) GetUserEmail() string {
//	if x != nil {
//		return x.UserEmail
//	}
//	return ""
//}
//
//func (x *UserRegisterRequest) GetUserPassword() string {
//	if x != nil {
//		return x.UserPassword
//	}
//	return ""
//}
//
//func (x *UserRegisterRequest) GetUserSessionId() string {
//	if x != nil {
//		return x.UserSessionId
//	}
//	return ""
//}
//
//type UserRegisterResponse struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Err int32  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
//	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
//}
//
//func (x *UserRegisterResponse) Reset() {
//	*x = UserRegisterResponse{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[10]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserRegisterResponse) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserRegisterResponse) ProtoMessage() {}
//
//func (x *UserRegisterResponse) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[10]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserRegisterResponse.ProtoReflect.Descriptor instead.
//func (*UserRegisterResponse) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{10}
//}
//
//func (x *UserRegisterResponse) GetErr() int32 {
//	if x != nil {
//		return x.Err
//	}
//	return 0
//}
//
//func (x *UserRegisterResponse) GetMsg() string {
//	if x != nil {
//		return x.Msg
//	}
//	return ""
//}
//
//type UserIndexResponseData struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	UserStatus int32  `protobuf:"varint,1,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
//	UserName   string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
//	Token      string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
//}
//
//func (x *UserIndexResponseData) Reset() {
//	*x = UserIndexResponseData{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[11]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserIndexResponseData) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserIndexResponseData) ProtoMessage() {}
//
//func (x *UserIndexResponseData) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[11]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserIndexResponseData.ProtoReflect.Descriptor instead.
//func (*UserIndexResponseData) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{2, 0}
//}
//
//func (x *UserIndexResponseData) GetUserStatus() int32 {
//	if x != nil {
//		return x.UserStatus
//	}
//	return 0
//}
//
//func (x *UserIndexResponseData) GetUserName() string {
//	if x != nil {
//		return x.UserName
//	}
//	return ""
//}
//
//func (x *UserIndexResponseData) GetToken() string {
//	if x != nil {
//		return x.Token
//	}
//	return ""
//}
//
//type UserRegisterResponseData struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	UserStatus int32  `protobuf:"varint,1,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
//	UserName   string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
//	Token      string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
//}
//
//func (x *UserRegisterResponseData) Reset() {
//	*x = UserRegisterResponseData{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_drink_proto_msgTypes[12]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *UserRegisterResponseData) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*UserRegisterResponseData) ProtoMessage() {}
//
//func (x *UserRegisterResponseData) ProtoReflect() protoreflect.Message {
//	mi := &file_drink_proto_msgTypes[12]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use UserRegisterResponseData.ProtoReflect.Descriptor instead.
//func (*UserRegisterResponseData) Descriptor() ([]byte, []int) {
//	return file_drink_proto_rawDescGZIP(), []int{10, 0}
//}
//
//func (x *UserRegisterResponseData) GetUserStatus() int32 {
//	if x != nil {
//		return x.UserStatus
//	}
//	return 0
//}
//
//func (x *UserRegisterResponseData) GetUserName() string {
//	if x != nil {
//		return x.UserName
//	}
//	return ""
//}
//
//func (x *UserRegisterResponseData) GetToken() string {
//	if x != nil {
//		return x.Token
//	}
//	return ""
//}
//
//var File_drink_proto protoreflect.FileDescriptor
//
//var file_drink_proto_rawDesc = []byte{
//	0x0a, 0x0b, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75,
//	0x73, 0x65, 0x72, 0x22, 0x82, 0x01, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x69,
//	0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
//	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
//	0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
//	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
//	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
//	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12,
//	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
//	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x61, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72,
//	0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
//	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
//	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
//	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
//	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
//	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x11,
//	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
//	0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
//	0x65, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
//	0x52, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x5a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a,
//	0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
//	0x28, 0x05, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b,
//	0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
//	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
//	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
//	0x6e, 0x22, 0x65, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71,
//	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d,
//	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
//	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
//	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f,
//	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x75, 0x73,
//	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5c, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72,
//	0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
//	0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x10,
//	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
//	0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
//	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
//	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x55, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70,
//	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
//	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
//	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
//	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61,
//	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0x38, 0x0a,
//	0x12, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
//	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
//	0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
//	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x49, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x44,
//	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
//	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
//	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61,
//	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61,
//	0x6d, 0x65, 0x22, 0x38, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
//	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
//	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
//	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x9e, 0x01, 0x0a,
//	0x13, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
//	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d,
//	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
//	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
//	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c,
//	0x12, 0x23, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
//	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73,
//	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65,
//	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
//	0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x96, 0x01,
//	0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
//	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20,
//	0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
//	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x5a, 0x0a, 0x04, 0x64, 0x61,
//	0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
//	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61,
//	0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
//	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
//	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
//	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2a, 0x39, 0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x55, 0x73,
//	0x65, 0x72, 0x53, 0x65, 0x78, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x45, 0x58, 0x5f, 0x49, 0x4e, 0x49,
//	0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x45, 0x58, 0x5f, 0x4d, 0x41, 0x4c, 0x45, 0x10,
//	0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x58, 0x5f, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10,
//	0x02, 0x32, 0xd2, 0x02, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x09, 0x55, 0x73,
//	0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55,
//	0x73, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
//	0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78,
//	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x08, 0x55, 0x73,
//	0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x12, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73,
//	0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
//	0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73,
//	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x55,
//	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65,
//	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
//	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
//	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x55, 0x73,
//	0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
//	0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
//	0x74, 0x1a, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c,
//	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a,
//	0x0c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x19, 0x2e,
//	0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
//	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
//	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
//	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x2f,
//	0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
//}
//
//var (
//	file_drink_proto_rawDescOnce sync.Once
//	file_drink_proto_rawDescData = file_drink_proto_rawDesc
//)
//
//func file_drink_proto_rawDescGZIP() []byte {
//	file_drink_proto_rawDescOnce.Do(func() {
//		file_drink_proto_rawDescData = protoimpl.X.CompressGZIP(file_drink_proto_rawDescData)
//	})
//	return file_drink_proto_rawDescData
//}
//
//var file_drink_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
//var file_drink_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
//var file_drink_proto_goTypes = []interface{}{
//	(EnumUserSex)(0),                 // 0: user.EnumUserSex
//	(*UserEntity)(nil),               // 1: user.UserEntity
//	(*UserIndexRequest)(nil),         // 2: user.UserIndexRequest
//	(*UserIndexResponse)(nil),        // 3: user.UserIndexResponse
//	(*UserViewRequest)(nil),          // 4: user.UserViewRequest
//	(*UserViewResponse)(nil),         // 5: user.UserViewResponse
//	(*UserUpdateRequest)(nil),        // 6: user.UserUpdateRequest
//	(*UserUpdateResponse)(nil),       // 7: user.UserUpdateResponse
//	(*UserDeleteRequest)(nil),        // 8: user.UserDeleteRequest
//	(*UserDeleteResponse)(nil),       // 9: user.UserDeleteResponse
//	(*UserRegisterRequest)(nil),      // 10: user.UserRegisterRequest
//	(*UserRegisterResponse)(nil),     // 11: user.UserRegisterResponse
//	(*UserIndexResponseData)(nil),    // 12: user.UserIndexResponse.data
//	(*UserRegisterResponseData)(nil), // 13: user.UserRegisterResponse.data
//}
//var file_drink_proto_depIdxs = []int32{
//	1,  // 0: user.UserViewResponse.data:type_name -> user.UserEntity
//	2,  // 1: user.User.UserIndex:input_type -> user.UserIndexRequest
//	4,  // 2: user.User.UserView:input_type -> user.UserViewRequest
//	6,  // 3: user.User.UserUpdate:input_type -> user.UserUpdateRequest
//	8,  // 4: user.User.UserDelete:input_type -> user.UserDeleteRequest
//	10, // 5: user.User.UserRegister:input_type -> user.UserRegisterRequest
//	3,  // 6: user.User.UserIndex:output_type -> user.UserIndexResponse
//	5,  // 7: user.User.UserView:output_type -> user.UserViewResponse
//	7,  // 8: user.User.UserUpdate:output_type -> user.UserUpdateResponse
//	9,  // 9: user.User.UserDelete:output_type -> user.UserDeleteResponse
//	11, // 10: user.User.UserRegister:output_type -> user.UserRegisterResponse
//	6,  // [6:11] is the sub-list for method output_type
//	1,  // [1:6] is the sub-list for method input_type
//	1,  // [1:1] is the sub-list for extension type_name
//	1,  // [1:1] is the sub-list for extension extendee
//	0,  // [0:1] is the sub-list for field type_name
//}
//
//func init() { file_drink_proto_init() }
//func file_drink_proto_init() {
//	if File_drink_proto != nil {
//		return
//	}
//	if !protoimpl.UnsafeEnabled {
//		file_drink_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserEntity); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserIndexRequest); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserIndexResponse); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserViewRequest); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserViewResponse); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserUpdateRequest); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserUpdateResponse); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserDeleteRequest); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserDeleteResponse); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserRegisterRequest); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserRegisterResponse); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserIndexResponseData); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_drink_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*UserRegisterResponseData); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//	}
//	type x struct{}
//	out := protoimpl.TypeBuilder{
//		File: protoimpl.DescBuilder{
//			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
//			RawDescriptor: file_drink_proto_rawDesc,
//			NumEnums:      1,
//			NumMessages:   13,
//			NumExtensions: 0,
//			NumServices:   1,
//		},
//		GoTypes:           file_drink_proto_goTypes,
//		DependencyIndexes: file_drink_proto_depIdxs,
//		EnumInfos:         file_drink_proto_enumTypes,
//		MessageInfos:      file_drink_proto_msgTypes,
//	}.Build()
//	File_drink_proto = out.File
//	file_drink_proto_rawDesc = nil
//	file_drink_proto_goTypes = nil
//	file_drink_proto_depIdxs = nil
//}
//
//// Reference imports to suppress errors if they are not otherwise used.
//var _ context.Context
//var _ grpc.ClientConnInterface
//
//// This is a compile-time assertion to ensure that this generated file
//// is compatible with the grpc package it is being compiled against.
//const _ = grpc.SupportPackageIsVersion6
//
//// UserClient is the client API for User service.
////
//// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
//type UserClient interface {
//	UserIndex(ctx context.Context, in *UserIndexRequest, opts ...grpc.CallOption) (*UserIndexResponse, error)
//	UserView(ctx context.Context, in *UserViewRequest, opts ...grpc.CallOption) (*UserViewResponse, error)
//	UserUpdate(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*UserUpdateResponse, error)
//	UserDelete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error)
//	UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error)
//}
//
//type userClient struct {
//	cc grpc.ClientConnInterface
//}
//
//func NewUserClient(cc grpc.ClientConnInterface) UserClient {
//	return &userClient{cc}
//}
//
//func (c *userClient) UserIndex(ctx context.Context, in *UserIndexRequest, opts ...grpc.CallOption) (*UserIndexResponse, error) {
//	out := new(UserIndexResponse)
//	err := c.cc.Invoke(ctx, "/user.User/UserIndex", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//func (c *userClient) UserView(ctx context.Context, in *UserViewRequest, opts ...grpc.CallOption) (*UserViewResponse, error) {
//	out := new(UserViewResponse)
//	err := c.cc.Invoke(ctx, "/user.User/UserView", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//func (c *userClient) UserUpdate(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*UserUpdateResponse, error) {
//	out := new(UserUpdateResponse)
//	err := c.cc.Invoke(ctx, "/user.User/UserUpdate", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//func (c *userClient) UserDelete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error) {
//	out := new(UserDeleteResponse)
//	err := c.cc.Invoke(ctx, "/user.User/UserDelete", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//func (c *userClient) UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error) {
//	out := new(UserRegisterResponse)
//	err := c.cc.Invoke(ctx, "/user.User/UserRegister", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//// UserServer is the server API for User service.
//type UserServer interface {
//	UserIndex(context.Context, *UserIndexRequest) (*UserIndexResponse, error)
//	UserView(context.Context, *UserViewRequest) (*UserViewResponse, error)
//	UserUpdate(context.Context, *UserUpdateRequest) (*UserUpdateResponse, error)
//	UserDelete(context.Context, *UserDeleteRequest) (*UserDeleteResponse, error)
//	UserRegister(context.Context, *UserRegisterRequest) (*UserRegisterResponse, error)
//}
//
//// UnimplementedUserServer can be embedded to have forward compatible implementations.
//type UnimplementedUserServer struct {
//}
//
//func (*UnimplementedUserServer) UserIndex(context.Context, *UserIndexRequest) (*UserIndexResponse, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method UserIndex not implemented")
//}
//func (*UnimplementedUserServer) UserView(context.Context, *UserViewRequest) (*UserViewResponse, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method UserView not implemented")
//}
//func (*UnimplementedUserServer) UserUpdate(context.Context, *UserUpdateRequest) (*UserUpdateResponse, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method UserUpdate not implemented")
//}
//func (*UnimplementedUserServer) UserDelete(context.Context, *UserDeleteRequest) (*UserDeleteResponse, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method UserDelete not implemented")
//}
//func (*UnimplementedUserServer) UserRegister(context.Context, *UserRegisterRequest) (*UserRegisterResponse, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method UserRegister not implemented")
//}
//
//func RegisterUserServer(s *grpc.Server, srv UserServer) {
//	s.RegisterService(&_User_serviceDesc, srv)
//}
//
//func _User_UserIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(UserIndexRequest)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(UserServer).UserIndex(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/user.User/UserIndex",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(UserServer).UserIndex(ctx, req.(*UserIndexRequest))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//func _User_UserView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(UserViewRequest)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(UserServer).UserView(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/user.User/UserView",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(UserServer).UserView(ctx, req.(*UserViewRequest))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//func _User_UserUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(UserUpdateRequest)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(UserServer).UserUpdate(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/user.User/UserUpdate",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(UserServer).UserUpdate(ctx, req.(*UserUpdateRequest))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//func _User_UserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(UserDeleteRequest)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(UserServer).UserDelete(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/user.User/UserDelete",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(UserServer).UserDelete(ctx, req.(*UserDeleteRequest))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//func _User_UserRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(UserRegisterRequest)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(UserServer).UserRegister(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/user.User/UserRegister",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(UserServer).UserRegister(ctx, req.(*UserRegisterRequest))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//var _User_serviceDesc = grpc.ServiceDesc{
//	ServiceName: "user.User",
//	HandlerType: (*UserServer)(nil),
//	Methods: []grpc.MethodDesc{
//		{
//			MethodName: "UserIndex",
//			Handler:    _User_UserIndex_Handler,
//		},
//		{
//			MethodName: "UserView",
//			Handler:    _User_UserView_Handler,
//		},
//		{
//			MethodName: "UserUpdate",
//			Handler:    _User_UserUpdate_Handler,
//		},
//		{
//			MethodName: "UserDelete",
//			Handler:    _User_UserDelete_Handler,
//		},
//		{
//			MethodName: "UserRegister",
//			Handler:    _User_UserRegister_Handler,
//		},
//	},
//	Streams:  []grpc.StreamDesc{},
//	Metadata: "drink.proto",
//}
